server:
  port: 9060

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html

#  web:
#    resources:
#      static-locations:

logging:
  level:
    org.springframework.web: trace