server:
  port: 9061


spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 289471259448-v8usv8hg163d56el2m56grc513dq683p.apps.googleusercontent.com
            clientSecret: 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
          naver:
            client-id: e4dr94KWpEFs87wJsiqJ
            client-secret: zbsSVqnoQi
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-name: naver
          kakao:
            client-id: 65a6f79a82a6c6fe0d8447d937bcf7b9
            client-secert: pLhLnn7qGhZ8P3AlbdsiaDhALwz2lfCW
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-name: kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id